### ISSUE TITLE
40GB rows.csv download

### ISSUE THREAD

**Issue by marklit** [toddwschneider/chicago-taxi-data#2]
Is it worth warning users the ``rows.csv`` file downloaded by ``download_raw_data.sh `` is uncompressed and it's around ~40GB in size?

**Comment by toddwschneider** [comment]
Sure, sounds reasonable. I added a note in the README but let me know if you were thinking of something else: https://github.com/toddwschneider/chicago-taxi-data/commit/087ce998d3439e51ebc45f336a90e79ab462711c#diff-04c6e90faac2675aa89e2176d2eec7d8R17

**Comment by marklit** [comment]
That's perfect. Cheers @toddwschneider
