### ISSUE TITLE
Adding new data

### ISSUE THREAD

**Issue by levyj** [toddwschneider/chicago-taxi-data#3]
I do not know if you (or anyone who may fork this project) are planning to keep the data up-to-date.  Re-downloading the whole dataset is, of course, safest but already takes a long time, as you note, and that time will only grow.

As one approach if you want to do incremental updates, the following API call (edited for the relevant dates) should work:

https://data.cityofchicago.org/resource/wrvz-psew.csv?$where=trip_start_timestamp%20between%20%272016-12-01T00:00%27%20and%20%272016-12-31T23:59%27&$limit=1000000000

The $limit term at the end is just to set an artificially high threshold to assure getting all records.  (There used to be a maximum per call but I think it has been removed.)

It probably would make some sense to pick a range somewhat overlapping the existing data and deduplicate off the Trip ID, just in case there were some changes.

**Comment by toddwschneider** [comment]
Thanks, this is a good idea! I'll add some kind of functionality to do an update as opposed to a full download

**Comment by toddwschneider** [comment]
@levyj take a look here: https://github.com/toddwschneider/chicago-taxi-data/pull/4

I added a script called `update_trips_data.sh` that downloads new data and updates the trips table, without having to download the full file
